services:
  api:  # This is the name of your todo app service
    build: .  # Tells Docker Compose to build the image from the Dockerfile in the current directory
    ports:
      - "3000:3000"  # Map port 8080 on your host machine to port 8080 in the container (adjust if necessary)
    depends_on:
      - postgres  # Ensure the database is running before your app starts
    environment:
      - DATABASE_URL
    restart: always

  postgres:
    image: postgres:17  # Or specify your desired PostgreSQL version
    env_file: .env
    ports:
      - "5432:5432"  # Load environment variables from .env file
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist data across container restarts
    restart: always

volumes:
  pgdata:  # Named volume for PostgreSQL data